CREATE TABLE IF NOT EXISTS rds_db_instance (
    id INT PRIMARY KEY AUTO_INCREMENT,
    db_instance_id VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(255),
    region_id VARCHAR(50),
    status VARCHAR(50),
    engine VARCHAR(50),
    engine_version VARCHAR(50),
    created_at DATETIME,
    updated_at DATETIME
);

-- 创建ECS实例表
CREATE TABLE IF NOT EXISTS `ecs_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `instance_id` varchar(64) NOT NULL COMMENT '实例ID',
  `host_name` varchar(128) DEFAULT NULL COMMENT '主机名',
  `memory` int DEFAULT NULL COMMENT '内存大小',
  `cpu` int DEFAULT NULL COMMENT 'CPU核数',
  `cpu_options` varchar(255) DEFAULT NULL COMMENT 'CPU选项',
  `internet_max_bandwidth_out` int DEFAULT NULL COMMENT '公网出带宽',
  `os_name` varchar(255) DEFAULT NULL COMMENT '操作系统名称',
  `image_id` varchar(64) DEFAULT NULL COMMENT '镜像ID',
  `status` varchar(32) DEFAULT NULL COMMENT '实例状态',
  `public_ip_address` varchar(255) DEFAULT NULL COMMENT '公网IP地址',
  `expired_time` datetime DEFAULT NULL COMMENT '过期时间',
  `instance_type` varchar(64) DEFAULT NULL COMMENT '实例类型',
  `region_id` varchar(32) DEFAULT NULL COMMENT '地域ID',
  `zone_id` varchar(32) DEFAULT NULL COMMENT '可用区ID',
  `instance_name` varchar(128) DEFAULT NULL COMMENT '实例名称',
  `description` varchar(255) DEFAULT NULL COMMENT '实例描述',
  `instance_type_family` varchar(64) DEFAULT NULL COMMENT '实例规格族',
  `os_type` varchar(32) DEFAULT NULL COMMENT '操作系统类型',
  `internet_charge_type` varchar(32) DEFAULT NULL COMMENT '网络计费类型',
  `internet_max_bandwidth_in` int DEFAULT NULL COMMENT '公网入带宽',
  `vpc_id` varchar(64) DEFAULT NULL COMMENT 'VPC ID',
  `v_switch_id` varchar(64) DEFAULT NULL COMMENT '交换机ID',
  `private_ip_address` varchar(255) DEFAULT NULL COMMENT '私网IP地址',
  `creation_time` datetime DEFAULT NULL COMMENT '创建时间',
  `start_time` datetime DEFAULT NULL COMMENT '启动时间',
  `created_at` datetime DEFAULT NULL COMMENT '记录创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_id` (`instance_id`),
  KEY `idx_status` (`status`),
  KEY `idx_region` (`region_id`),
  KEY `idx_zone` (`zone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ECS实例信息表'; 

-- 创建SLB负载均衡实例表
CREATE TABLE IF NOT EXISTS `slb_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `load_balancer_id` varchar(64) NOT NULL COMMENT '负载均衡实例ID',
  `load_balancer_name` varchar(128) DEFAULT NULL COMMENT '负载均衡实例名称',
  `load_balancer_status` varchar(32) DEFAULT NULL COMMENT '负载均衡实例状态',
  `address` varchar(64) DEFAULT NULL COMMENT '负载均衡实例服务地址',
  `ens_region_id` varchar(64) DEFAULT NULL COMMENT 'ENS节点ID',
  `network_id` varchar(64) DEFAULT NULL COMMENT '网络ID',
  `v_switch_id` varchar(64) DEFAULT NULL COMMENT '交换机ID',
  `create_time` datetime DEFAULT NULL COMMENT '负载均衡实例创建时间',
  `address_ip_version` varchar(16) DEFAULT NULL COMMENT 'IP版本',
  `pay_type` varchar(32) DEFAULT NULL COMMENT '付费类型',
  `region_id` varchar(32) DEFAULT NULL COMMENT '地域ID',
  `vpc_id` varchar(64) DEFAULT NULL COMMENT 'VPC ID',
  `address_type` varchar(32) DEFAULT NULL COMMENT '地址类型',
  `bandwidth` int DEFAULT NULL COMMENT '带宽',
  `master_zone_id` varchar(32) DEFAULT NULL COMMENT '主可用区ID',
  `slave_zone_id` varchar(32) DEFAULT NULL COMMENT '备可用区ID',
  `created_at` datetime DEFAULT NULL COMMENT '记录创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_load_balancer_id` (`load_balancer_id`),
  KEY `idx_slb_status` (`load_balancer_status`),
  KEY `idx_slb_region` (`region_id`),
  KEY `idx_slb_name` (`load_balancer_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SLB负载均衡实例信息表'; 

-- 创建系统监控数据表
CREATE TABLE IF NOT EXISTS `system_monitor` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `instance_id` varchar(64) NOT NULL COMMENT '实例ID',
  `cpu_usage` decimal(5,2) NOT NULL COMMENT 'CPU使用率(%)',
  `cpu_credit_balance` decimal(10,2) DEFAULT NULL COMMENT '突发性能实例积分总数',
  `cpu_credit_usage` decimal(10,2) DEFAULT NULL COMMENT '突发性能实例已使用的积分数',
  `cpu_notpaid_surplus_credit_usage` decimal(10,2) DEFAULT NULL COMMENT '超额未支付积分',
  `cpu_advance_credit_balance` decimal(10,2) DEFAULT NULL COMMENT '超额积分',
  `bps_read` bigint DEFAULT NULL COMMENT '云盘读带宽(Byte/s)',
  `bps_write` bigint DEFAULT NULL COMMENT '云盘写带宽(Byte/s)',
  `iops_read` bigint DEFAULT NULL COMMENT '云盘读IOPS(次/s)',
  `iops_write` bigint DEFAULT NULL COMMENT '云盘写IOPS(次/s)',
  `internet_bandwidth` bigint DEFAULT NULL COMMENT '公网带宽(kbits/s)',
  `intranet_bandwidth` bigint DEFAULT NULL COMMENT '内网带宽(kbits/s)',
  `internet_rx` bigint DEFAULT NULL COMMENT '公网入流量(kbits)',
  `internet_tx` bigint DEFAULT NULL COMMENT '公网出流量(kbits)',
  `intranet_rx` bigint DEFAULT NULL COMMENT '内网入流量(kbits)',
  `intranet_tx` bigint DEFAULT NULL COMMENT '内网出流量(kbits)',
  `monitor_time` datetime NOT NULL COMMENT '监控时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_instance_id` (`instance_id`),
  KEY `idx_monitor_time` (`monitor_time`),
  CONSTRAINT `fk_monitor_instance` FOREIGN KEY (`instance_id`) REFERENCES `ecs_instance` (`instance_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统监控数据表'; 